# Numpy Exercices

All the exercises in this section must be 100% Numpy. Each exercise should be at most 1-3 lines of code (so you should use Numpy's functions).

In [2]:
import numpy as np

## Initialize a null vector (with zeroes) of length 20.

In [2]:
null_vector = np.zeros(20)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Initialize a null matrix (with zeros) with size 3x2.

In [6]:
null_matrix = np.zeros((3,2))
print(null_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Initialize a vector with 10 random numbers between 0 and 1.

In [13]:
random_vector = np.random.random(size=10)
print(random_vector)

[0.88234185 0.13182843 0.38538987 0.15538261 0.7753979  0.12287654
 0.55545138 0.76432089 0.48278551 0.42136694]


## Replace the minimum element of the previous vector with a 0.

In [16]:
min = random_vector.argmin()
random_vector[min] = 0
print(random_vector)

[0.88234185 0.13182843 0.38538987 0.15538261 0.7753979  0.
 0.55545138 0.76432089 0.48278551 0.42136694]


## Create a vector with all consecutive values between 12 and 38.

In [19]:
consec_vector = np.arange(12,39)
print(consec_vector)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


## Initialize a vector of length 10 with integer random numbers between 1 and 20.

In [23]:
random_vector2 = np.random.randint(1,21, size=10)
print(random_vector2)

[14  4  8 19  9  3 10  8 20 13]


a) Filter the elements that are greater than 3 and less than 12.

In [24]:
random_vector2[(random_vector2 > 3) & (random_vector2 < 12)]

array([ 4,  8,  9, 10,  8])

b) Filter the elemetns that are less than or equal to 5 or greater than 15.

In [26]:
random_vector2[(random_vector2 <= 5) | (random_vector2 > 1)]

array([14,  4,  8, 19,  9,  3, 10,  8, 20, 13])

## Create a 4x4 matrix with integer random numbers between 0 and 5.

In [27]:
matrix = np.random.randint(0, 6, size=(4,4))
print(matrix)

[[4 2 0 2]
 [0 5 2 4]
 [5 2 4 5]
 [1 5 3 3]]


## Find the indices of the elements that are not 0 in the vector: [2, 1, 0, 0, 3, 1, 0].

In [33]:
v = np.array([2,1,0,0,3,1,0])
inde = np.where(v == 0)
print(inde)

(array([2, 3, 6], dtype=int64),)


## Create a random vector of length 10 and find the minimum, maximum, mean and standard deviation.

In [34]:
random_vector3 = np.random.randint(0,100,size = 10)
print(random_vector3)
mini = random_vector3.min()
maxi = random_vector3.max()
avg = random_vector3.mean()
stand_dev = random_vector3.std()
print(mini, maxi, avg, stand_dev)


[84 27 76 48 96 66 60 18 46 70]
18 96 59.1 23.34287899981491


## Create a 10x10 matrix with zeroes inside and ones surrounding them, like the following:

```
[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]
```

In [14]:
matrix = np.zeros((10,10))
matrix[0:1] = [1]
matrix[9:10] = [1]
matrix[:,0:1] = [1]
matrix[:,9:10] = [1]
matrix2 = np.ones((10,10))
matrix2[1:9,1:-1] = [0]
print(matrix)
print(matrix2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Defina a function that, given a vector, returns all the elements greater than 10 replaced by 0.

Example: [4, 7, 15, 21, 3, 34] → [4, 7, 0, 0, 3, 0]

In [15]:
v = np.array([4, 7, 15, 21, 3, 34])
v[v > 10] = 0
print(v)


[4 7 0 0 3 0]


## Define a function that negates (changes the sign) all the elements of a vector between 2 and 6.

Example: [4, 7, 15, 21, 3, 34] → [-4,  7, -6, 21, -3, 34]

In [16]:
v = np.array([4, 7, 15, 21, 3, 34])
v[(v>=2) & (v <=6)] *= (-1)
print(v)

[-4  7 15 21 -3 34]


## Define a function that returns the common elements between two vectors.

In [17]:
v1 = np.random.randint(0,5,size=10)
v2 = np.random.randint(0,5,size=10)
print(v1, v2)
com = np.intersect1d(v1,v2)
print(com)


[2 2 3 2 2 0 4 0 3 0] [3 3 4 3 1 3 1 3 3 1]
[3 4]


## Get the dates for today, yesterday and tomorrow.

In [21]:
today = np.datetime64("now", "D")
yesterday = today - np.timedelta64(1, "D")
tomorrow = today + np.timedelta64(1, "D")
print(today, yesterday, tomorrow)

2023-10-26 2023-10-25 2023-10-27


## Get all dates in September 2023.

In [29]:
sept = np.arange("2023-09", "2023-10", dtype="datetime64[D]")
print(sept)

['2023-09-01' '2023-09-02' '2023-09-03' '2023-09-04' '2023-09-05'
 '2023-09-06' '2023-09-07' '2023-09-08' '2023-09-09' '2023-09-10'
 '2023-09-11' '2023-09-12' '2023-09-13' '2023-09-14' '2023-09-15'
 '2023-09-16' '2023-09-17' '2023-09-18' '2023-09-19' '2023-09-20'
 '2023-09-21' '2023-09-22' '2023-09-23' '2023-09-24' '2023-09-25'
 '2023-09-26' '2023-09-27' '2023-09-28' '2023-09-29' '2023-09-30']


## Create an array of dates starting from today and covering the next 7 days.

In [30]:
today = np.datetime64("now", "D")
arr = np.arange(today, +7, dtype="datetime64[D]")
print(arr)

['2023-10-26' '2023-10-27' '2023-10-28' '2023-10-29' '2023-10-30'
 '2023-10-31' '2023-11-01']


## Given an array of dates, find the differences (in days) between each date and the first date in days.

In [32]:
dates = np.array(['2023-10-01', '2023-10-05', '2023-10-10', '2023-10-15'], dtype='datetime64')
difer = (dates - dates[0]).astype('timedelta64[D]')
print(difer)

[ 0  4  9 14]


## Create a random vector of length 10 with values between 0 and 1 (both included) and with 3 decimal points.

Note that by default `np.random.random()` does not include 1.

In [36]:
v = np.random.uniform(0,1, size= 10).round(3)
print(v)

[0.53  0.675 0.252 0.701 0.356 0.928 0.051 0.304 0.329 0.139]


## Create a random vector of length 10 and replace the maximum element with a 1 and the minimum with a 0.

In [39]:
v = np.random.uniform(0,10, size = 10)
print(v)
v[v.argmin()] = 0
v[v.argmax()] = 1
print(v)

[7.35492133 7.90132295 8.4571296  3.023562   0.45516514 6.87737456
 4.45644138 2.23949543 2.59720106 7.85133085]
[7.35492133 7.90132295 1.         3.023562   0.         6.87737456
 4.45644138 2.23949543 2.59720106 7.85133085]


## Define a function that, given a number N and a vector, returns the element closest to N. In case of a tie return the previous element.

In [50]:
def closest(arr, num):
    arr = np.array(arr)
    if num in arr:
        return num
    else:
        dif = np.abs(arr - num)
        ind = np.argmin(dif)
        return arr[ind]


In [45]:
assert closest([1, 2, 3, 4], 2) == 2
assert closest([1, 2, 3, 4], 5) == 4
assert closest([1, 2, 3, 4], -3) == 1
assert closest([1, 2, 2, 3, 4], 2) == 2
assert closest([1, 2, 2, 3, 4], 2.4) == 2
assert closest([1, 2, 2, 3, 4], 2.6) == 3

## Define a function that returns the N greater elements from a vector.

In [4]:
def elements(arr, n):
    return np.sort(arr)[-n:] 

l = [1,5,3,9,2,4]
elements(l,3)


array([4, 5, 9])

## Create a random vector of length 20 with values between 1 and 8. Which unique elements (without repetition) where created?

In [7]:
random_vector4 = np.random.randint(1,8, size = 20)
print(random_vector4)
print(np.unique(random_vector4))

[1 7 1 3 2 2 2 5 1 6 1 3 7 2 6 5 4 6 3 5]
[1 2 3 4 5 6 7]


## What will be the result of the following statements?

First try to understand the concepts of `np.nan`, `np.inf` and `set`. Next, try to mentally solve the statements by using your logic. Finally, test if your expected results are correct. 

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
```

In [11]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))

nan
False
False
nan
True


## Given a 10x10 matrix of random values between 0 and 1, find and print the row with the highest mean value.

In [19]:
matrix3 = np.random.uniform(0,1, size=(10,10))
high = np.argmax(np.mean(matrix3, axis=1))
print(matrix3[high])

[0.91108286 0.69385189 0.92922581 0.02279903 0.69295992 0.4374531
 0.92323716 0.36805042 0.73796206 0.51320943]


## Take two vectors of size 10 with random integers between 1 and 20. Compute the outer product of the two vectors, then flatten the resultant matrix into a one-dimensional array.

In [24]:
v1 = np.random.randint(1,20, size = 10)
v2 = np.random.randint(1,20, size = 10)
matrix = np.outer(v1,v2)
print(matrix)
print()
matrix = matrix.flatten()
print(matrix)

[[  8 104 128   8  16   8  32 104  56  56]
 [ 17 221 272  17  34  17  68 221 119 119]
 [ 16 208 256  16  32  16  64 208 112 112]
 [ 11 143 176  11  22  11  44 143  77  77]
 [ 14 182 224  14  28  14  56 182  98  98]
 [  7  91 112   7  14   7  28  91  49  49]
 [  8 104 128   8  16   8  32 104  56  56]
 [ 12 156 192  12  24  12  48 156  84  84]
 [ 11 143 176  11  22  11  44 143  77  77]
 [ 19 247 304  19  38  19  76 247 133 133]]

[  8 104 128   8  16   8  32 104  56  56  17 221 272  17  34  17  68 221
 119 119  16 208 256  16  32  16  64 208 112 112  11 143 176  11  22  11
  44 143  77  77  14 182 224  14  28  14  56 182  98  98   7  91 112   7
  14   7  28  91  49  49   8 104 128   8  16   8  32 104  56  56  12 156
 192  12  24  12  48 156  84  84  11 143 176  11  22  11  44 143  77  77
  19 247 304  19  38  19  76 247 133 133]


## Create an array of 100 consecutive dates starting from today. From this array, filter out all the dates that fall on a weekend (Saturday and Sunday).

In [29]:
today = np.datetime64("now", "D")
arr = np.arange(today, +100, dtype="datetime64[D]")
arr[(arr != 1) & (arr != 2) & ((arr % 8 == 0) | (arr % 9 == 0))]
print(arr)

C:\Users\Alumne_mati1\AppData\Local\Temp\ipykernel_9120\317624638.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  arr[(arr != 1) & (arr != 2) & ((arr % 8 == 0) | (arr % 9 == 0))]


UFuncTypeError: ufunc 'remainder' cannot use operands with types dtype('<M8[D]') and dtype('int32')

# Python vs Numpy

 For each one of the following exercises implement the functions using only Python, without any external libraries. Then compare the execution time with the `%%timeit` magic command (see the first example).

## Maximum

Write a function that find the maximum value of a list. Do not use the Python's `max()` function.

In [1]:
def my_max(l):
    # Find the maximum of a list of numbers
    mx = l[0]
    for e in l[1:]:
        if e > mx:
            mx = e
    return mx

In [2]:
tmp = np.random.randint(10, size=10000)

In [5]:
%%timeit

# My max
my_max(tmp)

594 µs ± 6.11 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
%%timeit

# Python's max
max(tmp)

455 µs ± 4.74 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
%%timeit

# Numpy's max
np.max(tmp)

8.1 µs ± 31.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Mean

Write a function that returns the mean of a list.

## Argmax

Write a function that returns the index of the greatest element of a list.

## Scalar Product

Write a function that returns the scalar product of two vectors.

# Bonus

##  One-hot Encoding

Implement a function that returns a matrix with the one-hot encoding of a vector.

- Example: 
    - Input: [0, 2, 1, 2, 0, 1]
    - Output:
```
[[1., 0., 0.],
[0., 0., 1.],
[0., 1., 0.],
[0., 0., 1.],
[1., 0., 0.],
[0., 1., 0.]]
```

## Fruit Ninja

You are a Fruit Ninja master, slicing fruits with precision. You have sliced 100 fruits, each giving you a random score between 1 and 100. However, due to a ninja technique, every third score is doubled. Calculate your total score.

## Time Traveler

A historian time traveler wants to study major events in the past century. Create an array of dates starting from 1923-08-14 to 2023-08-14 in 10-year increments, then randomly select 3 dates to travel to.

## Aliens

Aliens are sending messages, but it seems they're padding the real messages with a lot of zeros. Their messages are arrays of 100 elements with values either 0 or 1, but the real messages start and end with `1`. Extract their real message.

Challenge: Give a solution with at most 3 lines of code.

## Temperature Log

You have a 365-day temperature log for a city, represented as an array of floats. Identify the days where the temperature is at least 2 standard deviations away from the mean.

## Seismic Activity

Given a sequence of data representing seismic activity, where the values are floats, identify "earthquake" events. An earthquake is defined as a sequence where the readings rise continuously for at least 5 readings, peak, and then fall continuously for at least 5 readings.

Hint: Utilize Numpy's `gradient()` function to determine the rising and falling patterns in the sequence.

## Coin Flipping

A magician flips a coin 100 times, but his coin is tricky. It has a 70% chance of landing on heads (represented by 1) and 30% chance of tails (represented by 0). He asks you to predict how many times in a row the coin landed on heads at least 3 times.

Count every occurrence of 3 consecutive heads, including overlapping sequences. For example, in the sequence [1,1,1,1,0], the count is 2.

## The Game of Life

Implement "The Game of Live" using Numpy.